[package]
name = "advent-of-code-2021"
authors = ["Mirko von Leipzig <mirko.vonleipzig@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "aoc"

[dependencies]
